feign:
  client:
    config:
      default:
        connectTimeout: 200000
        readTimeout: 190000
        loggerLevel: FULL
        decode404: false
      currencyAppUrl:
        url: ${CURRENCY_APP_URL:http://localhost:9001/currency/api/}